import { browser } from "$app/environment";
import { isElectron, isElectronSession } from "$lib/use/useElectronEnv.svelte";
// Import constants generated by the script
// @ts-ignore
import { DEFAULT_LANG, SUPPORTED_LANGS } from "$src/i18ngen/constants";
import { matchLanguage } from "./negotiate";

export type Lang = (typeof SUPPORTED_LANGS)[number];
// User-configured language: a concrete language or 'system' (follow the
// browser language). Persisted in the cookie; in an embedded session it
// is reported to the host (webapp main) as the config value.
export type ConfigLang = Lang | "system";

// === DIRECT EXPORT OF RUNE ===
// This variable is imported by the generated static files.
// Svelte 5 tracks dependencies automatically when this is read.
let displayLang = $state<Lang>(DEFAULT_LANG);

// User-configured value ('system' | concrete), genuinely separate from
// displayLang: the display value may be overridden by the host downlink
// (embedded) or re-derived from the browser (system mode) without ever
// touching the config value. The cookie stores this, not displayLang, so
// a 'system' choice survives reloads.
let configLang = $state<ConfigLang>("system");

// === Helpers ===

function detectSystemLang(): Lang {
  return matchLanguage(navigator.languages, SUPPORTED_LANGS, DEFAULT_LANG) as Lang;
}

// Re-derive the display language from the config value.
function syncDisplayFromConfig() {
  displayLang = configLang === "system" ? detectSystemLang() : configLang;
}

// === Initialization ===
if (browser) {
  const match = document.cookie.match(new RegExp("(^| )alasio_lang=([^;]+)"));
  const saved = match ? match[2] : null;

  if (saved && (saved === "system" || (SUPPORTED_LANGS as readonly string[]).includes(saved))) {
    // Use saved preference ('system' included)
    configLang = saved as ConfigLang;
  } else {
    // No (valid) saved preference: default to follow system
    configLang = "system";
  }
  syncDisplayFromConfig();
}

// Browser language changes while in system mode: re-derive the display
// language (remote only — in an embedded session the host is the display
// authority and drives displayLang through the downlink). isElectron is
// only set after the first real downlink arrives, so the URL-parameter
// flag closes the pre-first-frame window (it never enables sync itself).
// The LangSelector $effect (ws set_lang negotiation) watches the display
// value and re-negotiates with the backend automatically.
if (browser) {
  window.addEventListener("languagechange", () => {
    if (configLang === "system" && !isElectron.value && !isElectronSession) syncDisplayFromConfig();
  });
}

/**
 * Apply a display language (always concrete) without reporting back to
 * the host. Used by the `alasio:lang` downlink: the host is the source
 * of truth, so host-driven changes must not loop back to it.
 *
 * The downlink also carries the host config value; it is applied so the
 * frontend configLang converges with the host (first-run guesses from
 * cookie/browser may differ). Remote sessions have no downlink and keep
 * the locally chosen configLang ('system' included) untouched.
 */
function applyLang(lang: Lang, config?: ConfigLang) {
  if (config !== undefined && config !== configLang) {
    configLang = config;
    if (browser) {
      document.cookie = `alasio_lang=${config}; path=/; max-age=31536000`;
    }
  }
  if (lang === displayLang) return;
  displayLang = lang;
}

/**
 * Report the user-chosen config value to the host (webapp main process).
 * The host is the source of truth: it derives the display language and
 * sends it back through the downlink. Remote browser sessions have no
 * parent container and never report.
 */
function reportLang(config: ConfigLang) {
  if (browser && isElectron.value) {
    window.parent.postMessage({ type: "alasio:lang", lang: config }, "*");
  }
}

// === Public API ===

/**
 * Switch language (user entry). Persists the config value to the cookie
 * and, in an embedded session, reports it to the host. 'system' derives
 * the display language from the browser locally; the host (embedded)
 * will override it with the derived value, and the backend negotiation
 * (ws set_lang RPC, watching displayLang) stays concrete.
 */
export function setLang(l: ConfigLang) {
  if (l === configLang) return;
  configLang = l;
  syncDisplayFromConfig();
  if (browser) {
    document.cookie = `alasio_lang=${l}; path=/; max-age=31536000`;
  }
  reportLang(l);
}

// Listen for the host-driven language downlink. The host sends the
// concrete display language whenever its config or system language
// changes, plus its config value so the frontend configLang converges
// with the host.
if (browser) {
  window.addEventListener("message", (event: MessageEvent) => {
    if (event.source !== window.parent) return;
    const data = event.data;
    if (!data || typeof data !== "object") return;
    if (data.type === "alasio:lang" && typeof data.lang === "string") {
      if ((SUPPORTED_LANGS as readonly string[]).includes(data.lang)) {
        const config = data.configLang;
        const validConfig =
          typeof config === "string" &&
          (config === "system" || (SUPPORTED_LANGS as readonly string[]).includes(config));
        applyLang(data.lang as Lang, validConfig ? (config as ConfigLang) : undefined);
      }
    }
  });
}

// Export state for read-only access if needed
export const i18nState = {
  get l() {
    return displayLang;
  },
  get configLang() {
    return configLang;
  },
};
