from alasio.assets_dev.extract import AssetsExtractor
from alasio.assets_dev.parse import AssetModule, AssetMultilang
from alasio.backport.suppress import suppress_keyboard_interrupt
from alasio.codegen.python import CodeGen
from alasio.config.const import Const
from alasio.ext.path import PathStr
from alasio.ext.path.calc import get_name, uppath


class AssetsExtractorALAS(AssetsExtractor):
    def patch_const(self):
        Const.ASSETS_PATH = 'assets'
        Const.ASSETS_MODULE = 'module'
        Const.ASSETS_LANG = dict.fromkeys(['cn', 'en', 'jp', 'tw'])

    def populate(self):
        # Alas don't have populate
        return

    def gen_asset(self, gen: "CodeGen", asset: "AssetMultilang"):
        """
        Generate code for an asset
        """
        if asset.asset.startswith('TEMPLATE_'):
            file = {}
            for lang in Const.ASSETS_LANG:
                data_frame = asset.dict_lang_frame.get(lang, {})
                if not data_frame:
                    data_frame = asset.dict_lang_frame.get('cn', {})
                for frame in data_frame.values():
                    file[lang] = './' + frame.path
                    # alas has only one frame
                    break
            with gen.Object(name=asset.asset, cls='Template').wrap('inline'):
                gen.Var(name='file', value=file)
        else:
            area = {}
            color = {}
            button = {}
            file = {}
            for lang in Const.ASSETS_LANG:
                data_frame = asset.dict_lang_frame.get(lang, {})
                if not data_frame:
                    data_frame = asset.dict_lang_frame.get('cn', {})
                for frame in data_frame.values():
                    area[lang] = frame.area
                    color[lang] = frame.color
                    button[lang] = frame.button
                    file[lang] = './' + frame.path
                    # alas has only one frame
                    break
            with gen.Object(name=asset.asset, cls='Button').wrap('inline'):
                gen.Var(name='area', value=area)
                gen.Var(name='color', value=color)
                gen.Var(name='button', value=button)
                gen.Var(name='file', value=file)

    def gen_module(self, gen: "CodeGen", module: "AssetModule"):
        """
        Generate code for a module
        """
        # header
        gen.FromImport('module.base.button').Import('Button')
        gen.FromImport('module.base.template').Import('Template')
        # This file was automatically generated by dev_tools/button_extract.py.
        # Don't modify it manually.
        gen.Comment("This file was automatically generated by dev_tools/button_extract.py.")
        gen.Comment("Don't modify it manually.")
        gen.Empty()

        # assets
        for asset in module:
            self.gen_asset(gen, asset)

    def get_output_file(self, module_path) -> "PathStr":
        """
        Args:
            module_path (str): example: "combat", "combat/support"

        Returns:
            output file of module
        """
        # module/combat/assets.py
        module, _, _ = module_path.partition('/')
        file = self.root.joinpath(f'{Const.ASSETS_MODULE}/{module}/assets.py')
        return file

    def file_to_module(self, file):
        # /assets/cn/combat/xxx.png -> combat
        path = get_name(uppath(file))
        return path

    @staticmethod
    def is_keep_file(file):
        """
        Args:
            file: Absolute filepath

        Returns:
            bool: True to keep this file in output directory
                False to remove it
        """
        # **DIFFERENCE** only remove assets.py in alas
        if file.endswith('assets.py'):
            return False
        return True


if __name__ == '__main__':
    with suppress_keyboard_interrupt():
        self = AssetsExtractorALAS(r'E:/ProgramData/pycharm/AzurLaneAutoScript')
        while 1:
            self.watch_files()
